### ISSUE TITLE
FASTQC_v2 null pointer exception

### ISSUE THREAD

**Issue by AaronNHart** [ibisngs/knime4ngs-src#3] opened 2019-04-09 13:37 UTC
I recently discovered this extension (and it looks very handy!) and am having a problem with the FastQC_v2 node throwing an exception.  Stack trace below.  I am working on Ubuntu 18 LTS, Java 8, KNIME 3.7 and fastqc 0.11.8.  Any idea what may be causing the issue?  If you can't reproduce but are open to an eventual pull request I can take a deeper look myself.  

Otherwise, this looks like a great project.  Kudos!

Aaron

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at de.helmholtz_muenchen.ibis.utils.threads.Executor.executeCommand(Executor.java:235)
	at de.helmholtz_muenchen.ibis.utils.abstractNodes.HTExecutorNode.HTExecutorNodeModel.executeCommand(HTExecutorNodeModel.java:347)
	at de.helmholtz_muenchen.ibis.utils.abstractNodes.HTExecutorNode.HTExecutorNodeModel.executeCommand(HTExecutorNodeModel.java:250)
	at de.helmholtz_muenchen.ibis.ngs.fastqc_v2.FastQC_v2NodeModel.execute(FastQC_v2NodeModel.java:168)

```

**Comment by timjeske** [comment] 2019-04-09 14:04
Hi Aaron, 

we are happy to hear that you want to use KNIME4NGS and thank you for reporting the issue.

We have a different system running here, so it might not be possible to directly reproduce the issue but maybe further information could already help to understand it:
1. Is any other node of KNIME4NGS properly running that executes an external binary?
2. It seems to me, that the error message you attached is not complete. There should be a "caused by" clause. Could you please add this, if you find this is part of your error message?

Kind regards
Tim

**Comment by AaronNHart** [comment] 2019-04-12 13:11
User error.  I did not have execute permissions on my fastqc binary.  Sorry about that!

**Comment by timjeske** [comment] 2019-04-12 13:12
Thank you for letting us know. So, I will close this issue.

**Closed as completed by timjeske** 2019-04-12 13:12 UTC
